name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print many greetings
        run: |
          echo "Hello World!"
          echo "Hey stalker ðŸ‘€"
      - name: Print goodbye
        run: echo "Done - bye~"
